name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy: # job *id* is Deploy
    name: Deploy # job display name is Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1" # or whatever version your project uses

      - name: Build the app
        run: |
          chmod +x scripts/buildprod.sh
          bash scripts/buildprod.sh
