name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy: # job *id* is Deploy
    name: Deploy # job display name is Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1" # or whatever version your project uses

      - name: Build the app
        run: |
          chmod +x scripts/buildprod.sh
          bash scripts/buildprod.sh
       - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud using Workload Identity Federation'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          # Your Google Cloud Project Number (from the dashboard: 1026851540891)
          project_id: ${{ env.PROJECT_ID }}
          # The Workload Identity Provider resource string:
          # projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
          workload_identity_provider: 'projects/1026851540891/locations/global/workloadIdentityPools/githubactions/providers/OIDC'
          # The email of the Service Account your CD will impersonate
          service_account: '[cloud-run-deployer@notely-475312.iam.gserviceaccount.com]'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Configure Docker to use gcloud as a credential helper'
        run: gcloud auth configure-docker "${{ env.GCR_HOSTNAME }}"

      - name: 'Build Docker image'
        run: docker build -t "${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .

      - name: 'Push Docker image to Google Container Registry'
        run: docker push "${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "${{ env.GCR_HOSTNAME }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
            --region us-central1 # Specify your desired region
            --platform managed \
            --allow-unauthenticated # Or remove if you need authentication