name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1026851540891/locations/global/workloadIdentityPools/githubactions/providers/github"
          service_account: "cloud-run-deployer@notely-475312.iam.gserviceaccount.com"

      # 3. Build and Push Image (This step can be kept or removed depending on your needs)
      #    If your new assignment is to only deploy a pre-existing image, you might not need to build it here.
      #    For this example, we assume the image is already built and available.

      # 4. Deploy the new image to Cloud Run with unauthenticated access
      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-475312/cloud-run-source-deploy/notely:${{ github.sha }} --region us-central1 --allow-unauthenticated --project notely-475312 --max-instances=4
