name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      # 1. Check out the repository code (which includes your Dockerfile)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1026851540891/locations/global/workloadIdentityPools/githubactions/providers/github"
          service_account: "cloud-run-deployer@notely-475312.iam.gserviceaccount.com"

      # 3. Deploy to Cloud Run (this will automatically use your Dockerfile)
      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "notely" # Your service name
          region: "europe-west1" # Your region
